app/event_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField, FileAllowed



class EventPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    text = TextAreaField('Text', validators=[DataRequired()])
    image =FileField('Update event Picture', validators=[FileAllowed(['jpg', 'png','jpeg'])])
    submit = SubmitField('CREATE Event')


class AddCommentForm(FlaskForm):
    body = StringField("Body", validators=[DataRequired()])
    submit = SubmitField("Post")

app/core/routes.py
from flask import render_template, request, Blueprint
from flask import url_for, redirect, send_file, jsonify
from app.models import EventPost
from flask_login import current_user, login_required
from datetime import datetime
from app import app, db
from flask import current_app
from app.task import create_file_in_background
from flask import g
from app.core.forms import SearchForm
import psycopg2


core = Blueprint('core', __name__)


@core.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    event_posts = EventPost.query.order_by(EventPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html',event_posts=event_posts)


@core.route('/info')
def info():
    return render_template('info.html')


@core.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()


@core.before_request
def before_request_s():
    g.search_form = SearchForm()


@core.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('core.index'))
    page = request.args.get('page', 1, type=int)
    posts, total = EventPost.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('core.search', q=g.search_form.q.data, page=page + 1) \
        if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('core.search', q=g.search_form.q.data, page=page - 1) \
        if page > 1 else None
    return render_template('search.html', title='Search', posts=posts,
                           next_url=next_url, prev_url=prev_url)


@core.route('/download_content', methods=['GET', 'POST'])
def download_content():
    task = create_file_in_background.apply_async()
    return jsonify({}), {'location': url_for('core.check_status', task_id=task.id)}


@core.route('/status/<task_id>', methods=['GET', 'POST'])
def check_status(task_id):
    task = create_file_in_background.AsyncResult(task_id)
    response = {
    'state': task.state
    }
    return jsonify(response)


@core.route('/download_start', methods=['GET'])
def download_start():
    return send_file('../a.json', as_attachment=True, cache_timeout=0)

app/event_posts/routes.py
from flask import Flask,render_template,url_for,flash, redirect,request,Blueprint
from flask_login import current_user,login_required
from app import db, app
from app.models import EventPost,Comment
from app.event_posts.forms import EventPostForm , AddCommentForm
from werkzeug.utils import secure_filename
import os

UPLOAD_FOLDER = './app/static/images'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])



event_posts = Blueprint('event_posts',__name__)

@event_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = EventPostForm()

    if form.validate_on_submit():
      file = request.files['image']
      if file.filename == '':
        flash('No image selected')
        return redirect(request.url)
      if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

        event_post = EventPost(title=form.title.data, text=form.text.data, event_image=os.path.join('../static/images', filename), user_id=current_user.id)
        db.session.add(event_post)
        db.session.commit()
        flash("Event Post Created")
        return redirect(url_for('core.index'))

    return render_template('create_post.html',form=form)


@event_posts.route('/<int:event_post_id>')
def event_post(event_post_id):
    event_post = EventPost.query.get_or_404(event_post_id)
    event_comment = Comment.query.filter_by(event_id=event_post_id)
    print(event_comment)
    return render_template('event_post.html',title=event_post.title,
                            date=event_post.date,post=event_post,event_comment=event_comment
    )

@event_posts.route("/<int:event_post_id>/update", methods=['GET', 'POST'])
@login_required
def update(event_post_id):
    event_post = EventPost.query.get_or_404(event_post_id)

    event_comment = Comment.query.filter_by(event_id=event_post_id).all()

    if event_post.author != current_user:
        abort(403)

    form = EventPostForm()
    if form.validate_on_submit():
        event_post.title = form.title.data
        event_post.text = form.text.data
        # event_post.event_image = form.image.data
        db.session.commit()
        flash('Post Updated')
        return redirect(url_for('event_posts.event_post', event_post_id=event_post.id))
    elif request.method == 'GET':
        form.title.data = event_post.title
        form.text.data = event_post.text
    return render_template('create_post.html', title='Update',
                           form=form)


@event_posts.route("/<int:event_post_id>/delete", methods=['POST'])
@login_required
def delete_post(event_post_id):
    event_post = EventPost.query.get_or_404(event_post_id)
    comment_post = event_post.comments.all()
    if event_post.author != current_user:
        abort(403)
    db.session.delete(event_post)
    for comment in comment_post:
        db.session.delete(comment)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))


@event_posts.route('/like/<int:post_id>/<action>')
@login_required
def like_action(post_id, action):
    post = EventPost.query.filter_by(id=post_id).first_or_404()
    if action == 'like':
        current_user.like_post(post)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    return redirect(request.referrer)




def allowed_file(filename):
   return '.' in filename and \
           filename.split('.')[-1].lower() in ALLOWED_EXTENSIONS






from flask import request

@event_posts.route("/post/<int:post_id>/comment", methods=["GET", "POST"])
@login_required
def comment_post(post_id):
    post = EventPost.query.get_or_404(post_id)
    form = AddCommentForm()
    if request.method == 'POST': # this only gets executed when the form is submitted and not when the page loads
        if form.validate_on_submit():
            comment = Comment(body=form.body.data, article=post, comment_author=current_user)
            db.session.add(comment)
            db.session.commit()
            flash("Your comment has been added to the post", "success")
            return redirect(url_for("event_posts.event_post", event_post_id=post.id))
    return render_template("comment_post.html", title="Comment Post",
form=form, post_id=post_id)

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, app
from werkzeug.security import generate_password_hash,check_password_hash
from app.models import User, EventPost
from app.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from app.users.picture_handler import add_profile_pic
from werkzeug.utils import secure_filename
import os
from config import Config

UPLOAD_FOLDER = './app/static/images'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
print(UPLOAD_FOLDER)



users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
      file = request.files['file']
      if file.filename == '':
        flash('No image selected')
        return redirect(request.url)
      if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data,
                    profile_image=os.path.join('../static/images', filename))

        db.session.add(user)
        db.session.commit()
        flash('Thanks for registering! Now you can login!')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user is not None and user.check_password(form.password.data):

            login_user(user)
            flash('Logged in successfully.')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')

            return redirect(next)
    return render_template('login.html', form=form)




@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():

    form = UpdateUserForm()

    if form.validate_on_submit():
        print(form)
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)


@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    event_posts = EventPost.query.filter_by(author=user).order_by(EventPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_event_posts.html', event_posts=event_posts, user=user)





def allowed_file(filename):
   return '.' in filename and \
           filename.split('.')[-1].lower() in ALLOWED_EXTENSIONS

app/templates/account.html
{% extends "base.html" %}
{% block content %}

<div class="jumbotron">
  <div align='center'>
    <h1 >Welcome to the page for {{current_user.username}}</h1>
    <img align='center' src="{{ url_for('static', filename= current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action = "" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      {{ form.username.label(class="form-group") }}
      {{form.username(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.email.label(class="form-group") }}
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group") }}
      {{ form.picture(class="form-control-file") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
  </form>

</div>

{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
  <ul class="nav">

  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('core.info') }}">About Us</a>
  </li>
    {% if current_user.is_authenticated %}
    <li class="nav-link"><a href="{{ url_for('users.logout') }}">Log Out</a></li>
    <li class="nav-link"><a href="{{ url_for('users.account') }}">Account</a></li>
    <li class="nav-link"><a href="{{ url_for('event_posts.create_post') }}">Create Event</a></li>
    {% else %}
    <li class="nav-link"><a href="{{ url_for('users.login') }}">Log In</a></li>
    <li class="nav-link"><a href="{{ url_for('users.register') }}">Register</a></li>
    {% endif %}

<li class="nav-link">
{% if g.search_form %}
 <form class="navbar-form navbar-left" method="get"
        action="{{ url_for('core.search') }}">
    <div class="form-group">
        {{ g.search_form.q(size=20, class='form-control',
            placeholder=g.search_form.q.label.text) }}
    </div>
  </form>
{% endif %}
</li>

</ul>


<div class="container">
  {% block content %}

  {% endblock %}

{%block app_content%}

    {% endblock %}

</div>


  </body>
</html>

app/templates/comment_post.html
{% extends "base.html"%}
{% block content %}
<div class="content-section">
        <form method="POST" action="{{url_for('event_posts.comment_post', post_id=(post_id))}}">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Comment</legend>
                <div class="form-group">
                    {{ form.body.label(class="form-control-label") }}
                    {% if form.body.errors %}
                        {{ form.body(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.body.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.body(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" name = "file" method="POST" enctype="multipart/form-data">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>

    <div class="form-group">
     <input type=file name="image">
    </div>

     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

app/templates/event_post.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Title: {{ post.title }}</h1>
  <h2>Created by : {{post.author.username}}</h2>
  <h3>Created on: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <h4>text: <p>{{post.text}}</p></h4>
  <div>
 <img align='center' src="{{ url_for('static', filename=post.event_image) }}">
  </div>
  {%if not current_user.is_anonymous%}
  {%if current_user.has_liked_post(post) %}
    <a href="{{ url_for('event_posts.like_action', post_id=post.id, action='unlike') }}">Unlike</a>



  {% else %}
    <a href="{{ url_for('event_posts.like_action', post_id=post.id, action='like') }}">Like</a>

  {% endif %}
  {% endif %}



  {{ post.likes.count() }} likes
  {{post.author.username}}

<br>
<hr>
<div>
  <p><b>Comments :</b></p>
  {%for comment in event_comment%}
  <p><b>{{comment.comment_author.username}}:</b>
  {{comment.body}}</p>
  {%endfor%}
  <br>
</div>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('event_posts.update', event_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <!-- Modal for Pop Up-->
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this event?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('event_posts.delete_post', event_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>The Event</h1>
    <p>Welcome to Our Company's Page</p>
  </div>

  <div class="container">

    {# Go through each event post #}
    {% for post in event_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('event_posts.event_post', event_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Created on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('event_posts.event_post', event_post_id=post.id) }}" class="btn btn-primary">Read Event</a>
        {%if not current_user.is_anonymous%}
        <a href="{{ url_for('event_posts.comment_post', post_id=post.id) }}" class="btn btn-primary">comment</a>
        {%if current_user.has_liked_post(post) %}

        <a href="{{ url_for('event_posts.like_action', post_id=post.id, action='unlike') }}">Unlike</a>
        {% else %}
        <a href="{{ url_for('event_posts.like_action', post_id=post.id, action='like') }}">Like</a>
        {% endif %}
        {% endif %}
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in event_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if event_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

app/templates/info.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1>Info about our Company</h1>
  <p>The Event is a platform that lets you discover the best in events. We strive to curate experiences that are worth your time and money, possibly something you have never tried before..</p>
</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block content %}
<form method="POST">
    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}
{% block content %}
<form method="POST" name = "file" enctype="multipart/form-data">

    {# This hidden_tag is a CSRF security feature. #}
    {{ form.hidden_tag() }}
    {{ form.email.label }} {{ form.email() }}<br>
    <input type=file name= "file">
    {{ form.username.label }} {{ form.username() }}<br>
    {{ form.password.label }} {{ form.password() }}<br>
    {{ form.pass_confirm.label }} {{ form.pass_confirm() }}<br>
    {{ form.submit() }}
</form>
{% endblock %}

app/templates/search.html
{% block app_content %}
    <h1>{{ ('Search Results') }}</h1>
    {% for post in posts %}
        {% include 'event_post.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span>
                    {{ ('Previous results') }}
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    {{ ('Next results') }}
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/user_event_posts.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <!-- <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}"> -->

      <div>

<button class='btn' onclick="download()">download </button>

<a style = "display:none;" href="{{ url_for('core.download_start') }}"><button class='btn btn-success' id='hidden-download'>download_start</button></a>




  </div>
  <img align='center' src="{{ url_for('static', filename=user.profile_image) }}">
  </div>
  </div>


{% for post in event_posts.items %}

          <h2><a href="{{ url_for('event_posts.event_post', event_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Created on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in event_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if event_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              </li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>

<script type="text/javascript">

function download() {
  $.ajax({
    'url': "{{ url_for('core.download_content') }}",
    'type': "GET",
    'success': function (data, status, request) {
      status = request.getResponseHeader('Location');
      status_check(status)
    }
  });
}


function status_check(task_status) {
  $.ajax({
    'url': task_status,
    'type': "GET",
    'success': function (data) {
      if ((data['state'] == 'PENDING') || (data['state'] =='PROGRESS')) {
        setTimeout(function () {
          status_check(task_status);
        }, 2000);
      } else {
        document.getElementById('hidden-download').click();
      };
    }
  });
}

</script>

{% endblock content %}